# Generated by Django 5.2.17 on 2026-09-15 20:15

import apps.privacy.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Acesso"),
                            ("CORRECTION", "Correção"),
                            ("PORTABILITY", "Portabilidade"),
                            ("ANONYMIZATION", "Anonimização"),
                            ("DELETION", "Exclusão"),
                            ("CONSENT_REVIEW", "Revisão de consentimento"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("IN_REVIEW", "Em análise"),
                            ("FULFILLED", "Atendida"),
                            ("REJECTED", "Rejeitada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                ("requester_name", models.CharField(max_length=255)),
                ("requester_email", models.EmailField(blank=True, max_length=254)),
                (
                    "due_date",
                    models.DateField(default=apps.privacy.models.default_due_date),
                ),
                ("response_summary", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_subject_requests",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_data_subject_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handled_data_subject_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_subject_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_subject_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "status", "due_date"],
                        name="privacy_dat_clinic__34d0a4_idx",
                    ),
                    models.Index(
                        fields=["patient", "request_type", "created_at"],
                        name="privacy_dat_patient_c0e8c8_idx",
                    ),
                ],
            },
        ),
    ]
