# Generated by Django 5.2.17 on 2026-09-15 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelehealthSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING_ROOM", "Sala de espera"),
                            ("IN_PROGRESS", "Em atendimento"),
                            ("FINISHED", "Finalizada"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="WAITING_ROOM",
                        max_length=16,
                    ),
                ),
                (
                    "provider",
                    models.CharField(blank=True, default="internal", max_length=64),
                ),
                ("external_room_id", models.CharField(max_length=120, unique=True)),
                ("join_url", models.URLField(blank=True)),
                ("expires_at", models.DateTimeField()),
                ("waiting_room_open", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telehealth_session",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telehealth_sessions",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_telehealth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["appointment__date", "appointment__start_time"],
            },
        ),
        migrations.CreateModel(
            name="TelehealthParticipantEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PROFESSIONAL", "Profissional"),
                            ("PATIENT", "Paciente"),
                            ("GUARDIAN", "Responsável"),
                            ("STAFF", "Equipe"),
                        ],
                        max_length=16,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telehealth_participant_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_events",
                        to="telehealth.telehealthsession",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="telehealthsession",
            index=models.Index(
                fields=["clinic", "status", "is_active"],
                name="telehealth__clinic__8a6f09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="telehealthparticipantevent",
            index=models.Index(
                fields=["session", "role", "joined_at"],
                name="telehealth__session_42c27f_idx",
            ),
        ),
    ]
