# Generated by Django 5.2.17 on 2026-09-15 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telehealth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelehealthAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PROFESSIONAL", "Profissional"),
                            ("PATIENT", "Paciente"),
                            ("GUARDIAN", "Responsável"),
                            ("STAFF", "Equipe"),
                        ],
                        default="PATIENT",
                        max_length=16,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_tokens",
                        to="telehealth.telehealthsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["token", "expires_at"],
                        name="telehealth__token_7663c0_idx",
                    )
                ],
            },
        ),
    ]
