# Generated by Django 5.2.17 on 2026-09-15 13:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        ("professionals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecordEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("EVOLUTION", "Evolução"),
                            ("SESSION_NOTE", "Nota de sessão"),
                            ("INITIAL_ASSESSMENT", "Avaliação inicial"),
                        ],
                        default="EVOLUTION",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("FINAL", "Finalizado"),
                            ("VOIDED", "Anulado"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record_entries",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record_entries",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_medical_record_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record_entries",
                        to="patients.patient",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record_entries",
                        to="professionals.professional",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_medical_record_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecordAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Criado"),
                            ("UPDATED", "Atualizado"),
                            ("VOIDED", "Anulado"),
                        ],
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record_audit_events",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="medical_records.medicalrecordentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecordEntryVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("EVOLUTION", "Evolução"),
                            ("SESSION_NOTE", "Nota de sessão"),
                            ("INITIAL_ASSESSMENT", "Avaliação inicial"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("FINAL", "Finalizado"),
                            ("VOIDED", "Anulado"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_record_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="medical_records.medicalrecordentry",
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
            },
        ),
        migrations.AddIndex(
            model_name="medicalrecordentry",
            index=models.Index(
                fields=["clinic", "patient", "is_active"],
                name="medical_rec_clinic__4abe83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecordentry",
            index=models.Index(
                fields=["professional", "created_at"],
                name="medical_rec_profess_02d64a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecordauditevent",
            index=models.Index(
                fields=["clinic", "created_at"], name="medical_rec_clinic__9ba627_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="medicalrecordentryversion",
            constraint=models.UniqueConstraint(
                fields=("entry", "version"), name="unique_medical_record_entry_version"
            ),
        ),
    ]
