# Generated by Django 5.2.17 on 2026-09-15 19:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("CLINIC", "Clínica"),
                            ("PROFESSIONAL", "Profissional"),
                        ],
                        default="CLINIC",
                        max_length=16,
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_professionals", models.PositiveIntegerField(default=1)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["monthly_price", "name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("OPEN", "Aberta"),
                            ("PAID", "Paga"),
                            ("CANCELLED", "Cancelada"),
                            ("REFUNDED", "Reembolsada"),
                            ("OVERDUE", "Vencida"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("external_invoice_id", models.CharField(blank=True, max_length=120)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Dinheiro"),
                            ("PIX", "Pix"),
                            ("BANK_TRANSFER", "Transferência"),
                            ("CREDIT_CARD", "Cartão de crédito"),
                            ("DEBIT_CARD", "Cartão de débito"),
                            ("EXTERNAL_GATEWAY", "Gateway externo"),
                            ("OTHER", "Outro"),
                        ],
                        default="PIX",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("AUTHORIZED", "Autorizado"),
                            ("PAID", "Pago"),
                            ("FAILED", "Falhou"),
                            ("CANCELLED", "Cancelado"),
                            ("REFUNDED", "Reembolsado"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("gateway", models.CharField(blank=True, max_length=80)),
                ("external_payment_id", models.CharField(blank=True, max_length=120)),
                ("card_brand", models.CharField(blank=True, max_length=32)),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIALING", "Em teste"),
                            ("ACTIVE", "Ativa"),
                            ("PAST_DUE", "Em atraso"),
                            ("CANCELLED", "Cancelada"),
                            ("EXPIRED", "Expirada"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                (
                    "starts_at",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("ends_at", models.DateField(blank=True, null=True)),
                ("trial_ends_at", models.DateField(blank=True, null=True)),
                (
                    "external_subscription_id",
                    models.CharField(blank=True, max_length=120),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CHARGE", "Cobrança"),
                            ("REFUND", "Reembolso"),
                            ("CANCELLATION", "Cancelamento"),
                            ("ADJUSTMENT", "Ajuste"),
                        ],
                        default="CHARGE",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["clinic", "status", "is_active"],
                name="billing_inv_clinic__20372f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["patient", "created_at"], name="billing_inv_patient_9fc9fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["clinic", "status", "paid_at"],
                name="billing_pay_clinic__a90a48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["clinic", "status"], name="billing_sub_clinic__2024ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["clinic", "transaction_type", "created_at"],
                name="billing_tra_clinic__275851_idx",
            ),
        ),
    ]
