# Generated by Django 5.2.17 on 2026-09-22 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RECEPTIONIST", "Recepção/Secretaria"),
                            ("FINANCE", "Financeiro"),
                            ("ADMINISTRATIVE", "Administrativo"),
                            ("OPERATIONAL", "Operacional"),
                            ("ACCOUNTANT", "Contador"),
                            ("CLEANING", "Limpeza"),
                            ("OTHER", "Outro"),
                        ],
                        default="ADMINISTRATIVE",
                        max_length=32,
                    ),
                ),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("position", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("INACTIVE", "Inativo"),
                            ("BLOCKED", "Bloqueado"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("access_enabled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "status", "is_active"],
                        name="clinics_cli_clinic__f5e690_idx",
                    ),
                    models.Index(
                        fields=["clinic", "role"], name="clinics_cli_clinic__e18304_idx"
                    ),
                ],
            },
        ),
    ]
