# Generated by Django 5.2.17 on 2026-09-15 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Especialidade",
                "verbose_name_plural": "Especialidades",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("social_name", models.CharField(blank=True, max_length=255)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("profession", models.CharField(max_length=120)),
                ("crp", models.CharField(blank=True, max_length=32)),
                ("crp_state", models.CharField(blank=True, max_length=2)),
                ("registration_number", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("INACTIVE", "Inativo"),
                            ("BLOCKED", "Bloqueado"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("biography", models.TextField(blank=True)),
                (
                    "appointment_modalities",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "Presencial"),
                            ("ONLINE", "Online"),
                            ("HYBRID", "Híbrido"),
                        ],
                        default="IN_PERSON",
                        max_length=16,
                    ),
                ),
                (
                    "appointment_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "default_appointment_duration",
                    models.PositiveSmallIntegerField(default=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professionals",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professional_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="professionals",
                        to="professionals.specialty",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "is_active"],
                        name="professiona_clinic__d3e1ef_idx",
                    ),
                    models.Index(
                        fields=["clinic", "status"],
                        name="professiona_clinic__1d0126_idx",
                    ),
                ],
            },
        ),
    ]
