# Generated by Django 5.2.17 on 2026-09-15 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        ("professionals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("DECLARATION", "Declaração"),
                            ("CONSENT", "Consentimento"),
                            ("REPORT", "Relatório"),
                            ("RECEIPT", "Recibo"),
                            ("OTHER", "Outro"),
                        ],
                        default="DECLARATION",
                        max_length=24,
                    ),
                ),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_templates",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_document_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("FINAL", "Finalizado"),
                            ("SIGNED", "Assinado"),
                            ("VOIDED", "Anulado"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_generated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to="professionals.professional",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_documents",
                        to="documents.documenttemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_generated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["clinic", "is_active"], name="documents_d_clinic__374ad4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                fields=("clinic", "name"),
                name="unique_document_template_name_per_clinic",
            ),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(
                fields=["clinic", "status", "is_active"],
                name="documents_g_clinic__a07e0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(
                fields=["patient", "created_at"], name="documents_g_patient_fed61f_idx"
            ),
        ),
    ]
