# Generated by Django 5.2.17 on 2026-09-15 19:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("INFORMED_CONSENT", "Termo de consentimento"),
                            ("PRIVACY_POLICY", "Política de privacidade"),
                            ("TELEHEALTH", "Teleatendimento"),
                            ("DATA_PROCESSING", "Tratamento de dados"),
                            ("SPECIFIC_AUTHORIZATION", "Autorização específica"),
                            ("OTHER", "Outro"),
                        ],
                        default="INFORMED_CONSENT",
                        max_length=32,
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                ("body", models.TextField()),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_templates",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_consent_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title", "version"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Aceito"),
                            ("REJECTED", "Recusado"),
                            ("REVOKED", "Revogado"),
                        ],
                        default="ACCEPTED",
                        max_length=16,
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("document_title", models.CharField(max_length=180)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INFORMED_CONSENT", "Termo de consentimento"),
                            ("PRIVACY_POLICY", "Política de privacidade"),
                            ("TELEHEALTH", "Teleatendimento"),
                            ("DATA_PROCESSING", "Tratamento de dados"),
                            ("SPECIFIC_AUTHORIZATION", "Autorização específica"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=32,
                    ),
                ),
                ("document_version", models.CharField(max_length=32)),
                ("document_body", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_records",
                        to="patients.patient",
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subject_consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="consents.consenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consenttemplate",
            index=models.Index(
                fields=["clinic", "template_type", "is_active"],
                name="consents_co_clinic__ef0bcb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="consenttemplate",
            constraint=models.UniqueConstraint(
                fields=("clinic", "title", "version"),
                name="unique_consent_template_version_per_clinic",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["clinic", "status", "accepted_at"],
                name="consents_co_clinic__4806a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["patient", "template", "accepted_at"],
                name="consents_co_patient_e973b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentrecord",
            index=models.Index(
                fields=["subject_user", "template", "accepted_at"],
                name="consents_co_subject_3ee513_idx",
            ),
        ),
    ]
