# Generated by Django 5.2.17 on 2026-09-22 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


INITIAL_INSTRUMENTS = [
    {"code": "bai", "name": "BAI - Inventário de Ansiedade de Beck", "category": "Ansiedade"},
    {"code": "bfp", "name": "BFP - Bateria Fatorial de Personalidade", "category": "Personalidade"},
    {"code": "bpa2", "name": "BPA-2 - Bateria Psicológica para Avaliação da Atenção", "category": "Atenção"},
    {"code": "cars2_hf", "name": "CARS2-HF - Childhood Autism Rating Scale, Second Edition", "category": "Social / Autismo"},
    {"code": "ebadep_a", "name": "EBADEP-A - Escala Baptista de Depressão Adulto", "category": "Depressão"},
    {"code": "ebadep_ij", "name": "EBADEP-IJ - Escala Baptista de Depressão Infantojuvenil", "category": "Depressão"},
    {"code": "epq_j", "name": "EPQ-J - Questionário de Personalidade para Crianças e Jovens", "category": "Personalidade"},
    {"code": "etdah_ad", "name": "ETDAH-AD - Escala de TDAH para Adultos", "category": "Atenção / TDAH"},
    {"code": "etdah_pais", "name": "ETDAH-Pais - Escala de TDAH respondida por pais", "category": "Atenção / TDAH"},
    {"code": "fdt", "name": "FDT - Teste dos Cinco Dígitos", "category": "Funções executivas"},
    {"code": "mchat", "name": "M-CHAT - Modified Checklist for Autism in Toddlers", "category": "Social / Autismo"},
    {"code": "ravlt", "name": "RAVLT - Teste de Aprendizagem Auditivo-Verbal de Rey", "category": "Memória"},
    {"code": "scared", "name": "SCARED - Screen for Child Anxiety Related Emotional Disorders", "category": "Ansiedade"},
    {"code": "srs2", "name": "SRS-2 - Escala de Responsividade Social", "category": "Social / Autismo"},
    {"code": "ssrs", "name": "SSRS - Sistema de Avaliação de Habilidades Sociais", "category": "Social / Comportamento"},
    {"code": "wais3", "name": "WAIS-III - Escala Wechsler de Inteligência para Adultos", "category": "Inteligência"},
    {"code": "wasi", "name": "WASI - Escala Wechsler Abreviada de Inteligência", "category": "Inteligência"},
    {"code": "wisc4", "name": "WISC-IV - Escala Wechsler de Inteligência para Crianças", "category": "Inteligência"},
]


def seed_initial_instruments(apps, schema_editor):
    AssessmentInstrument = apps.get_model(
        "psychological_assessments",
        "AssessmentInstrument",
    )
    for instrument in INITIAL_INSTRUMENTS:
        AssessmentInstrument.objects.get_or_create(
            code=instrument["code"],
            defaults={
                "name": instrument["name"],
                "category": instrument["category"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("psychological_assessments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="classified_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="computed_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="interpretation_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="reviewed_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="psychological_assessments.assessmentinstrument",
            ),
        ),
        migrations.RunPython(seed_initial_instruments, migrations.RunPython.noop),
    ]
