# Generated by Django 5.2.17 on 2026-09-22 15:09

from django.conf import settings
from django.db import migrations, models


def backfill_assessment_codes(apps, schema_editor):
    Assessment = apps.get_model("psychological_assessments", "Assessment")
    AssessmentCodeCounter = apps.get_model(
        "psychological_assessments",
        "AssessmentCodeCounter",
    )
    counters: dict[int, int] = {}

    for assessment in Assessment.objects.order_by("created_at", "id"):
        if assessment.status == "DRAFT":
            assessment.status = "PLANNING"
        if not assessment.code:
            year = assessment.created_at.year if assessment.created_at else 2026
            counters[year] = counters.get(year, 1)
            assessment.code = f"AV-{year}-{counters[year]:06d}"
            counters[year] += 1
        assessment.save(update_fields=["status", "code"])

    for year, next_number in counters.items():
        AssessmentCodeCounter.objects.update_or_create(
            year=year,
            defaults={"next_number": next_number},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_clinicstaff"),
        ("patients", "0002_patient_intake_fields"),
        ("professionals", "0001_initial"),
        ("psychological_assessments", "0002_assessmentinstrument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentCodeCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(unique=True)),
                ("next_number", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["year"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("PSYCHOLOGICAL", "Psicológica"),
                    ("NEUROPSYCHOLOGICAL", "Neuropsicológica"),
                    ("PSYCHODIAGNOSTIC", "Psicodiagnóstica"),
                    ("BEHAVIORAL", "Comportamental"),
                    ("DEVELOPMENT", "Desenvolvimento"),
                    ("OTHER", "Outra"),
                ],
                default="PSYCHOLOGICAL",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="demand_origin",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="assessment",
            name="expected_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="objective",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="requester",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.RunPython(backfill_assessment_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNING", "Planejamento"),
                    ("IN_PROGRESS", "Em andamento"),
                    ("WAITING_INFORMATION", "Aguardando informação"),
                    ("WRITING", "Em elaboração"),
                    ("WAITING_FEEDBACK", "Aguardando devolutiva"),
                    ("COMPLETED", "Concluída"),
                    ("CANCELLED", "Cancelada"),
                ],
                default="PLANNING",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["clinic", "code"], name="psychologic_clinic__656fc3_idx"
            ),
        ),
    ]
