# Generated by Django 5.2.17 on 2026-09-22 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0001_initial"),
        (
            "psychological_assessments",
            "0003_assessmentcodecounter_assessment_assessment_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_assessment_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="modality",
            field=models.CharField(
                choices=[
                    ("IN_PERSON", "Presencial"),
                    ("ONLINE", "Online"),
                    ("OTHER", "Outra"),
                ],
                default="IN_PERSON",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="objective",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="permitted_observations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="procedures",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="professional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessment_sessions",
                to="professionals.professional",
            ),
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_assessment_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AssessmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField(blank=True)),
                ("hypotheses", models.TextField(blank=True)),
                ("domains", models.JSONField(blank=True, default=list)),
                ("procedures", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="psychological_assessments.assessment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_assessment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "planned_instruments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planned_assessments",
                        to="psychological_assessments.assessmentinstrument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_assessment_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
