# Generated by Django 5.2.17 on 2026-09-22 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psychological_assessments", "0005_assessment_cancellation_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentresult",
            name="void_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentresult",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="voided_assessment_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assessmenttimelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Criada"),
                    ("UPDATED", "Atualizada"),
                    ("PLANNED", "Planejamento"),
                    ("SESSION_REGISTERED", "Sessão registrada"),
                    ("RESULT_CREATED", "Resultado criado"),
                    ("RESULT_FINALIZED", "Resultado finalizado"),
                    ("RESULT_VOIDED", "Resultado anulado"),
                    ("CANCELLED", "Cancelada"),
                ],
                max_length=32,
            ),
        ),
    ]
