# Generated by Django 5.2.17 on 2026-09-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0001_initial"),
        ("psychological_assessments", "0006_assessmentresult_void_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentapplication",
            name="applied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applied_assessment_instruments",
                to="professionals.professional",
            ),
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instrumentapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_assessment_instruments",
                to="professionals.professional",
            ),
        ),
    ]
