# Generated by Django 5.2.17 on 2026-09-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychological_assessments', '0007_instrumentapplication_applied_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentinstrument',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='max_age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Idade máxima em meses', null=True),
        ),
        migrations.AddField(
            model_name='assessmentinstrument',
            name='min_age_months',
            field=models.PositiveIntegerField(blank=True, help_text='Idade mínima em meses', null=True),
        ),
    ]
