# Generated by Django 5.2.17 on 2026-09-15 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("professionals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("social_name", models.CharField(blank=True, max_length=255)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Feminino"),
                            ("MALE", "Masculino"),
                            ("OTHER", "Outro"),
                            ("NOT_INFORMED", "Não informado"),
                        ],
                        default="NOT_INFORMED",
                        max_length=16,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("INACTIVE", "Inativo"),
                            ("ARCHIVED", "Arquivado"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=80)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("has_authorization", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="ProfessionalPatient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_links",
                        to="patients.patient",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_links",
                        to="professionals.professional",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "is_active"], name="patients_pa_clinic__009fa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic", "status"], name="patients_pa_clinic__d8d066_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="professionalpatient",
            index=models.Index(
                fields=["patient", "professional", "is_active"],
                name="patients_pr_patient_f37cc8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="professionalpatient",
            constraint=models.UniqueConstraint(
                fields=("patient", "professional"),
                name="unique_patient_professional_link",
            ),
        ),
    ]
