# Generated by Django 5.2.17 on 2026-09-15 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login realizado"),
                            ("LOGIN_FAILED", "Login falhou"),
                            ("LOGOUT", "Logout"),
                            ("MFA_CHALLENGE", "Desafio MFA"),
                            ("MFA_ENABLED", "MFA ativado"),
                            ("MFA_DISABLED", "MFA desativado"),
                            ("MEDICAL_RECORD_VIEWED", "Prontuário visualizado"),
                            ("DOCUMENT_DOWNLOADED", "Documento baixado"),
                            ("PERMISSION_CHANGED", "Permissão alterada"),
                            ("ADMIN_ACCESS", "Acesso administrativo"),
                            ("DATA_REQUEST_CREATED", "Solicitação LGPD criada"),
                            ("DATA_REQUEST_UPDATED", "Solicitação LGPD atualizada"),
                        ],
                        max_length=32,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=120)),
                ("resource_id", models.CharField(blank=True, max_length=120)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "action", "created_at"],
                        name="audit_audit_clinic__39c179_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_audit_actor_i_58da28_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_audit_resourc_2ab5ff_idx",
                    ),
                ],
            },
        ),
    ]
