# Generated by Django 5.2.17 on 2026-09-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login realizado"),
                    ("LOGIN_FAILED", "Login falhou"),
                    ("LOGOUT", "Logout"),
                    ("MFA_CHALLENGE", "Desafio MFA"),
                    ("MFA_ENABLED", "MFA ativado"),
                    ("MFA_DISABLED", "MFA desativado"),
                    ("MEDICAL_RECORD_VIEWED", "Prontuário visualizado"),
                    ("DOCUMENT_DOWNLOADED", "Documento baixado"),
                    ("PERMISSION_CHANGED", "Permissão alterada"),
                    ("ADMIN_ACCESS", "Acesso administrativo"),
                    ("DATA_REQUEST_CREATED", "Solicitação LGPD criada"),
                    ("DATA_REQUEST_UPDATED", "Solicitação LGPD atualizada"),
                    ("ASSESSMENT_CREATE", "Avaliação criada"),
                    ("ASSESSMENT_UPDATE", "Avaliação atualizada"),
                    ("ASSESSMENT_CANCEL", "Avaliação cancelada"),
                    ("ASSESSMENT_RESULT_FINALIZE", "Resultado de avaliação finalizado"),
                    ("ASSESSMENT_RESULT_VOID", "Resultado de avaliação anulado"),
                ],
                max_length=32,
            ),
        ),
    ]
