# Generated by Django 5.2.17 on 2026-09-15 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinics", "0001_initial"),
        ("patients", "0001_initial"),
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "Presencial"),
                            ("ONLINE", "Online"),
                            ("HYBRID", "Híbrido"),
                        ],
                        default="IN_PERSON",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Agendada"),
                            ("CONFIRMED", "Confirmada"),
                            ("IN_PROGRESS", "Em atendimento"),
                            ("COMPLETED", "Concluída"),
                            ("CANCELLED", "Cancelada"),
                            ("NO_SHOW", "Faltou"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("administrative_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="professionals.professional",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "date"], name="appointment_clinic__f6186d_idx"
                    ),
                    models.Index(
                        fields=["professional", "date", "start_time"],
                        name="appointment_profess_520f4d_idx",
                    ),
                    models.Index(
                        fields=["patient", "date"],
                        name="appointment_patient_83aa7a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScheduleBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_blocks",
                        to="clinics.clinic",
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_blocks",
                        to="professionals.professional",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["professional", "date", "is_active"],
                        name="appointment_profess_2bac8e_idx",
                    )
                ],
            },
        ),
    ]
